### ISSUE TITLE
A question about the BN layer

### ISSUE THREAD

**Issue by wzm2256** [hichoe95/WGAN_GP_CelebAHQ#1]
Hi, thanks for sharing your code.

I just read through your code and see the use of BN layer in the discriminator. I'd like to ask whether that caused any problem in the training, because in theory that will makes the gradient penalty loss useless. In the paper <Improved..>, the author suggest using Layer normalization instead of BN layer, but I did not find any further information about this.

**Comment by hichoe95** [comment]
I have not used any normalization in Discriminator, since the Convblock of discriminator has 'down' option. 
But I hadn't even considered that part. I will correct it by referring to the paper again and will add the 'layer norm' and 'None' options for discriminator in arguments.
Thank you for the information!

**Comment by wzm2256** [comment]
You are welcome, and thanks again for your sharing your code :)
